name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: |
        cd app
        npm ci
        
    - name: Run tests
      run: |
        cd app
        npm test || true

    - name: Build Docker image
      run: docker build -t kairos-tasks ./app
